export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_ERRORS = 'GET_ERRORS';
export const LOADING_ENABLE = 'LOADING_ENABLE';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const RESET_CART = 'RESET_CART';